services:
  - type: web
    name: enterprise-hrms-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build --prefix backend
    startCommand: npm run start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 10000
